### ISSUE TITLE
DeprecationWarning: Buffer()

### ISSUE THREAD

**Issue by renanlido** [sand4rt/ftp-deployer#10]
(node:1714) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

![image](https://user-images.githubusercontent.com/25422117/147151823-05ec6f0f-957b-427e-bd9c-218872d847bb.png)

**Comment by rod-laycock** [comment]
Same here - does not deploy

**Comment by rod-laycock** [comment]
> Same here - does not deploy

Found an alternative using - milanmk/actions-file-deployer@1.10

**Comment by sand4rt** [comment]
Duplicate of https://github.com/sand4rt/ftp-deployer/issues/4
