### ISSUE TITLE
Include and Exclude incorrect formatting

### ISSUE THREAD

**Issue by MoMoneyRiches** [sand4rt/ftp-deployer#11]
The example given in the readme for the include and exclude is incorrect formatting. Should change it to this

```
    include: [] # optional, e.g. '["dist"]'
    exclude: [] # optional, e.g. '["node_modules/**", ".git/**", "*.env"]'
```

**Comment by sand4rt** [comment]
Fixed in: https://github.com/sand4rt/ftp-deployer/commit/507ed402058a303fd286718801d09cf63582813e
