### ISSUE TITLE
Error: dist/ is not an existing location

### ISSUE THREAD

**Issue by Ben1nBlack** [sand4rt/ftp-deployer#17]
I really appreciate, the effort you put into this. 

in github actions i get error:

`Run sand4rt/ftp-deployer@v1.5
Deploying...
(node:1656) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Err dist/ is not an existing location
Error: Error: dist/ is not an existing location`

here is snippet for YAML
`jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: FTP Deployer
        uses: sand4rt/ftp-deployer@v1.5
        with:
          sftp: false # optional
          host: ${{ secrets.CF_FTP_SERVER }} # e.g. ftp.host.com or sftp.host.com (without ftp:// or ftps://)
          port: 21 # optional, default is: 21
          username: ${{ secrets.CF_FTP_USER_NAME }} # FTP username
          password: ${{ secrets.CF_FTP_USER_PASS }} # FTP password
          remote_folder: "demo/" # optional, remote path of your FTP server
          local_folder: "dist/" # optional, local path, default is: dist
          cleanup: false # optional, remove existing files inside FTP remote folder
          exclude: '["node_modules/**",".git/**","*.env,img/**","images/**","Backups/**","logs/**","ups2csv/**","Witango5Admin/**","CFSITEMAP-ALPHA_files/**","CFSITEMAP_files/**","aspnet_client/**"]'
          passive: true`

please note I have tried
1. local_folder: "dist/" # optional, local path, default is: dist
2. local_folder: dist/ # optional, local path, default is: dist
3. local_folder: dist # optional, local path, default is: dist
4. i removed the local_folder: and still git same error

**Comment by sand4rt** [comment]
Hi @Ben1nBlack, does this work in v1.4?

**Comment by sand4rt** [comment]
Closed due to inactivity. Feel free to create a new issue if needed.
