### ISSUE TITLE
Remove pasive from readme (for version 1.5)

### ISSUE THREAD

**Issue by BaseMax** [sand4rt/ftp-deployer#21]
**Warning: Unexpected input(s) 'pasive', valid inputs are ['sftp', 'host', 'port', 'username', 'password', 'remote_folder', 'local_folder', 'cleanup', 'include', 'exclude', 'passive']**

It seems "pasive" not supported in version 1.5 but it supported in version 1.4

**Comment by BaseMax** [comment]
maybe need to rename to passive. because passive supported in version 1.5.

**Comment by sand4rt** [comment]
Correct in v1.5 it's renamed to from pasive to passive: https://github.com/sand4rt/ftp-deployer/pull/14
