### ISSUE TITLE
Upgrade to use Node.js 20

### ISSUE THREAD

**Issue by lwarner-tb** [sand4rt/ftp-deployer#23]
Github requires upgrade of actions to use Node.js 20. Build annotation using this project:

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: sand4rt/ftp-deployer@v1.7. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

**Comment by sand4rt** [comment]
@lwarner-tb thanks for creating the issue, could you verify if this Is fixed in v1.8?

**Comment by lwarner-tb** [comment]
It's fixed! Thanks for the very quick response!
