### ISSUE TITLE
DeprecationWarning: Buffer() is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by Comver** [sand4rt/ftp-deployer#4]
Run sand4rt/ftp-deployer@v1.1
(node:3021) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Deploying...
/home/runner/work/_actions/sand4rt/ftp-deployer/v1.1/dist/index.js:11609
          return reentry();
          ^

ReferenceError: reentry is not defined
    at /home/runner/work/_actions/sand4rt/ftp-deployer/v1.1/dist/index.js:11609:11
    at Socket.<anonymous> (/home/runner/work/_actions/sand4rt/ftp-deployer/v1.1/dist/index.js:11668:7)
    at Object.onceWrapper (events.js:300:26)
    at Socket.emit (events.js:210:5)
    at TCP.<anonymous> (net.js:659:12)

**Comment by cgsmith** [comment]
@sand4rt How did you create the distribution file?

**Comment by sand4rt** [comment]
@cgsmith I'm using another package called ftp-deploy that is causing this error: https://github.com/simonh1000/ftp-deploy/issues/116. Let me know if you want to know more.

**Comment by cgsmith** [comment]
I'm curious how you generated the distribution file? Was this bult separately or downloaded elsewhere? Trying to test a few things locally.

**Comment by sand4rt** [comment]
You mean the dist folder? This is generated by running `npm install` and after that run: `npm run build`.

1. `npm install` installs the `ncc` command 
2. `npm run build` runs `ncc build index.js`
3. In the `index.js` file, i import a library called `ftp-deploy` _(which has a pagent.exe included)_

Noting is downloaded from elsewhere _(only from npm through the packages.json)_

**Comment by sand4rt** [comment]
This is how you can test the deployment:
1. create a test-action.js in the root of the git repository
2. run `npm install && npm run build`
3. Paste the code below in the created test-action.js
4. Change the host, user, password properties 
5. run `node test-action.js`

```JavaScript
const core = require('@actions/core');
const FtpDeploy = require('ftp-deploy');

core.info('Deploying...');

new FtpDeploy()
    .deploy({
        sftp: true,
        host: 'test.rebex.net',
        port: 22,
        user: 'demo',
        password: 'password',
        remoteRoot: './',
        localRoot: 'dist',
        include:  ['dist'],
        exclude: ['node_modules/**', 'node_modules/**/.*', '.git/**']
    }) 
    .then(response => core.info('Deploy finished:', response))
    .catch(error => core.error(error));
```

**Comment by sand4rt** [comment]
Does this still persist after v1.7?
