### ISSUE TITLE
JSONparse error when using the example with exclude

### ISSUE THREAD

**Issue by Matt-17** [sand4rt/ftp-deployer#8]
After trying a while, I figured out, it must be
   exclude:  '["node_modules/**", ".git/**", "*.env"]'

The whole array must be in a string and all values must be in double ". 

Also I get this warning: 
(node:2932) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by sand4rt** [comment]
Thanks for creating the issue. Fancy to open a PR and fix the parser? line 15 till 18 needs refactoring: https://github.com/sand4rt/ftp-deployer/blob/master/index.js#L15

**Comment by sand4rt** [comment]
Fixed in: https://github.com/sand4rt/ftp-deployer/commit/507ed402058a303fd286718801d09cf63582813e
